from .dashboard import dashboard
from .index import index
from .settings import settings
from .role import role
from .login import login
from .medical_tool import medical_tool
from .reagen import reagen
from .check_category_services import check_category_services
from .sample_category_services import sample_category_services
from .patient import patient
